ccflags-y += -I$(ZEPHYR_BASE)/samples/linde_v13/src/fs/fatfs/drivers
ccflags-y += -I$(ZEPHYR_BASE)/samples/linde_v13/src/fs/fatfs
ccflags-y += -I$(ZEPHYR_BASE)/samples/linde_v13/src/fs
ccflags-y += -I$(ZEPHYR_BASE)/samples/linde_v13/src/fs/fatfs/option

obj-y += fatfs_mmc_sdio.o
