ccflags-y += -I$(ZEPHYR_BASE)/samples/linde_v13/src/fs
ccflags-y += -I$(ZEPHYR_BASE)/samples/linde_v13/src/fs/fatfs
ccflags-y += -I$(ZEPHYR_BASE)/samples/linde_v13/src/fs/fatfs/drivers

obj-y += drivers/
obj-y += option/
obj-y += diskio.o
obj-y += ff.o
